apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pynzxqg9f-go 
  janus-idp.io/tekton: pynzxqg9f-go
  backstage.io/kubernetes-id: pynzxqg9f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pynzxqg9f-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  